### PR TITLE
fix: use random `buildDir` to avoid conflicts

### LINKED ISSUE #52: fix: build conflict between multiple tests
Originally reported by #50, when having multiple `.test` files, jest runs them in parallel. If two depending on a single fixture and need build, this causes issues. Some options are:

- Using run-in-band to disable parallel run
- Using a lock-file so one test awaits on others during build
- Using random build ids for `buildDir`
- Using mfs (#49) for building in mem (considering all internals can support)

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #52

### CODE REVIEW

File: src/nuxt.ts [hunk 1]
```diff
@@ -22,6 +22,10 @@ export async function loadFixture () {
   if (!ctx.config.rootDir) {
     ctx.config.rootDir = ctx.rootDir
   }
+
+  if (!ctx.config.buildDir) {
+    ctx.config.buildDir = resolve(ctx.rootDir, '.nuxt', ctx._id.toString())
```
Comment (pi0) [inline src/nuxt.ts:27]: This id is not unique across multiple test files unless manually set...
